# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      run: make build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Test
      run: make test
  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Package .deb      
      run: make deb
    - name: deb artifact
      uses: actions/upload-artifact@v4      
      with:
        name: deb-package_2        
        path: myprogram.deb
  deploy:    
    needs: package
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4      
      - name: Download .deb artifact
        uses: actions/download-artifact@v4        
        with:
          name: deb-package_2          
          path: .
      - name: Build Docker image        
        run: |
          chmod +x lab
          docker build -t my-lab-app .          
      - name: Run Docker container        
        run: |
          chmod +x lab         
      - name: Save Docker image as tar file        
        run: |
          docker save -o my-lab-app.tar my-lab-app
      - name: Upload Docker image as artifact        
        uses: actions/upload-artifact@v4
        with:
          name: my-lab-app          
          path: my-lab-app.tar
